import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'model.dart';

class Profile extends StatefulWidget {
  const Profile({Key? key}) : super(key: key);
  _ProfileState createState() => _ProfileState();
}

class _ProfileState extends State<Profile> {
  List<Autogenerated> autolist = [];

  Future<List<Autogenerated>> getApi() async {
    final response =
        await http.get(Uri.parse("https://jsonplaceholder.typicode.com/posts"));
    var data = jsonDecode(response.body.toString());
    if (response.statusCode == 200) {
      autolist.clear();
      for (Map i in data) {
        autolist.add(Autogenerated.fromJson(i));
      }
      return autolist;
    } else {
      return autolist;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.amber,
        title: Text('Profile'),
        centerTitle: true,
      ),
      body: Column(
        children: <Widget>[
          Expanded(
              child: FutureBuilder(
                  future: getApi(),
                  builder: (context, snapshot) {
                    if (!snapshot.hasData) {
                      return Text('Loading');
                    } else {
                      return ListView.builder(itemBuilder: (context, index) {
                        return Card(
                            child: Column(
                          children: [
                            Text(autolist[index].id.toString()),
                            Text(autolist[index].userId.toString()),
                            Text(autolist[index].title.toString()),
                            Text(autolist[index].body.toString()),
                          ],
                        ));
                      });
                    }
                  }))
        ],
      ),
    );
  }
}
